### ISSUE TITLE
你们确定 ios的小程序能支持webp格式么？

### ISSUE THREAD

**Issue by MrKou47** [upyun/upyun-wxapp-sdk#1]
为什么我这边在ios调试 不显示webp的图片呢？

**Comment by CatTail** [comment]
1. 使用什么版本的代码？
2. 图片是否上传成功？如果不成功，报错内容是什么？
3. 有问题的图片地址是什么？

**Comment by MrKou47** [comment]
- ios 版本: 10.3.1
- 微信版本 6.5.7
- 图片地址 `http://img.loookapp.cn/online/20170420/e79a194e4d9e8ca49d5942bb289b5d9c-largeWebp`

可以把这个链接放在 `image` 标签里，然后在ios上看一下，我这边是不显示图片的
我这里只是想确认一下 小程序是否支持 webp。 如果确认能支持的话能否提供一个小程序体验一下？

**Comment by CatTail** [comment]
经测试确认 iOS 微信小程序 `image` 标签不能正常显示 webp 格式图片。
