### ISSUE TITLE
微信小程序打开报错

### ISSUE THREAD

**Issue by jiangyoucai** [upyun/upyun-wxapp-sdk#3]
WAService.js:15 Uncaught Error: module "utils/upyun-wxapp-sdk.js" is not defined
    at require (WAService.js:15)
    at WAService.js:15
    at index.js? [sm]:1
    at require (WAService.js:15)
    at appservice:1090

**Comment by sabakugaara** [comment]
稍等

**Comment by HogwartsRico** [comment]
把根目录下的upyun-wxapp-sdk.js放到demo/utils下
